# Generated by Django 4.0.1 on 2022-01-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='overiew',
            new_name='overview',
        ),
    ]
