# Generated by Django 4.0.1 on 2022-01-08 15:52

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_overiew_course_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attach',
            field=models.FileField(blank=True, upload_to=course.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
